--PROBLEM 1
SELECT * FROM SYSIBM.SYSTABLES WHERE CREATOR = 'HBW42431';

--PROBLEM 2
DELETE FROM SYSIBM.SYSTABLES WHERE NAME='EMPLOYEES';

--PROBLEM 3
DROP TABLE EMPLOYEES;

--PROBLEM 4
SELECT * FROM SYSIBM.SYSTABLES WHERE CREATOR = 'HBW42431';